edx-olive/edx-platform-old

requirements/edx/github.txt

This fixes a vulnerability, see [SE-829](https://tasks.opencraft.com/browse/SE-829)

Update django-wiki version

---

lms/templates/support/certificates.html

This has already been patched in the upstream master branch

Fix XSS vulnerability in the Certificates Support page

---

common/lib/capa/capa/capa_problem.py
common/lib/capa/capa/tests/test_capa_problem.py

Patch ironwood capa problem
(cherry picked from commit b4dd41841fbfc312aade9d89cc50b98a6a8e444c)
**Related PRs**
- https://github.com/edx/edx-platform/pull/23102
- https://github.com/open-craft/edx-platform/pull/211

[SE-2326] Merge pull request #23102 from edx/patch-ironwood-capa-problem

---

cms/static/js/models/uploads.js

Cf. [SE-2550](https://tasks.opencraft.com/browse/SE-2550)
**Reviewers**

Security patch for file upload XSS issue (Studio).

---

cms/static/js/index.js
cms/static/js/views/edit_chapter.js

Cf. [SE-2550](https://tasks.opencraft.com/browse/SE-2550)
**Reviewers**

Security patch for edit_chapter XSS lint issues (Studio).

---

cms/static/js/index.js

Cf. [SE-2550](https://tasks.opencraft.com/browse/SE-2550)
**Reviewers**

Finish applying security patch for XSS issue on library page.

---

requirements/edx/base.txt

This PR updates the social-auth-app-django and social-auth-core library versions.
Deployed to stage.campus.gov.il
1. Go to https://stage.campus.gov.il/ and sign-up with Google account or Facebook account.
2. Ensure sign-up goes through without any errors. 
**Reviewers:**

Update social-auth library versions

---

cms/static/js/certificates/views/certificate_editor.js
cms/static/js/certificates/views/certificate_preview.js
cms/static/js/certificates/views/signatory_details.js
cms/static/js/certificates/views/signatory_editor.js
cms/static/js/maintenance/force_publish_course.js
cms/static/js/models/settings/course_details.js
cms/static/js/models/settings/course_grading_policy.js
cms/static/js/views/abstract_editor.js
cms/static/js/views/asset.js
cms/static/js/views/course_info_handout.js
openedx/core/djangoapps/cors_csrf/templates/cors_csrf/xdomain_proxy.html
themes/stanford-style/lms/templates/courseware/course_about_sidebar_header.html

Sustaining xsslint security fixes
(cherry picked from commit edd9b02d520f7bf4dadc110ab46455556325dc93)
---
**Test instructions**:
- check code against upstream commit and look for bad merges
- deploy to campus stage
- check functionality in areas where these fixes changed things: certificates, whatever course info handout.js manages
**Reviewers**:

SE-2898 Cherry pick xss fixes 

---

lms/templates/student_account/register.underscore
lms/templates/student_profile/badge_list.underscore
lms/templates/student_profile/badge_placeholder.underscore
lms/templates/verify_student/test/fake_softwaresecure_response.html

Small PR to apply the required XSS security fix.

Apply XSS security fix

---

cms/static/js/views/components/add_xblock.js
cms/static/js/views/components/add_xblock_button.js
cms/static/js/views/course_rerun.js
cms/static/js/views/instructor_info.js
cms/static/js/views/list_item_editor.js
cms/static/js/views/metadata.js
cms/static/js/views/video/translations_editor.js
cms/static/js/views/xblock_validation.js

PR to apply the required edX security XSS patch.

Apply XSS security patch

---

cms/static/js/views/baseview.js
cms/static/js/views/license.js
cms/static/js/views/list.js
cms/static/js/views/manage_users_and_roles.js
cms/static/js/views/uploads.js
cms/static/js/views/video/transcripts/message_manager.js
cms/static/js/views/xblock_string_field_editor.js
cms/templates/js/course_info_handouts.underscore
cms/templates/js/grading-editor.underscore
cms/templates/js/metadata-string-entry.underscore
cms/templates/js/section-name-edit.underscore
cms/templates/js/signatory-actions.underscore
cms/templates/js/team-member.underscore
cms/templates/js/video/transcripts/messages/transcripts-import.underscore
cms/templates/js/video/transcripts/messages/transcripts-not-found.underscore
cms/templates/js/video/transcripts/messages/transcripts-replace.underscore
cms/templates/js/video/transcripts/messages/transcripts-uploaded.underscore
cms/templates/js/video/transcripts/messages/transcripts-use-existing.underscore
cms/templates/js/xblock-outline.underscore

This pull request is about backporting XSS fixes from [BB-2941](https://tasks.opencraft.com/browse/BB-2941).
**Jira tickets**
- [SE-3236](https://tasks.opencraft.com/browse/SE-3236)
- [BB-2941](https://tasks.opencraft.com/browse/BB-2941)
**Testing instructions**
TBA
**Reviewers**
TBA

[SE-3236] Apply XSS patches

---

requirements/edx/base.txt

**Test instructions**:
- see https://github.com/open-craft/edx-sga/pull/1
**Reviewers**:

SE-3566 Use patched version of edx-sga

---

cms/static/js/models/settings/course_grader.js
cms/static/js/views/active_video_upload.js
common/djangoapps/third_party_auth/templates/third_party_auth/post_custom_auth_entry.html
common/lib/xmodule/xmodule/js/src/collapsible.js
common/lib/xmodule/xmodule/js/src/video/09_poster.js
lms/static/js/api_admin/views/catalog_preview.js
lms/static/js/discovery/views/filter_bar.js

Cherry picks xss security fixes.
* **Jira Tickets**: SE-4361
* **Related Pull Requests**: https://github.com/edx/edx-platform/pull/27228, https://github.com/edx/edx-platform/pull/27394
* **Related Forum Posts**: [_Security: IM patch for xss fixes 10_](https://discuss.openedx.org/t/security-im-patch-for-xss-fixes-10/4702/1), [_Security patch for xss fixes_](https://discuss.openedx.org/t/security-patch-for-xss-fixes/4820/1)
* Follow the [instance test checklist](https://handbook.opencraft.com/en/latest/test_checklist/)
ASAP

backport: cherry picks upstream xss security fixes

---

lms/djangoapps/periodic_instructor_reports/tasks.py

This PR makes it possible to generate periodic instructor reports for all ccx related to a course, including or excluding the course itself.
**Screenshots**: 
**Sandbox URL**: N/A
**Merge deadline**: None
TBD
**Author notes and concerns**:
N/A
**Reviewers**

[SE-4370] feat: generate reports for ccx belonging to a course

---

cms/celery.py
common/static/common/js/discussion/utils.js
lms/celery.py

This PR applies the recent security patches to the custom gingko branch.
**Sandbox URL**: Deployed to Stage
Do a sanity check and ensure nothing is broken because of these fixes
**Reviewers:**

[SE-4689] Backport recent security fixes to Gingko

---

common/lib/xmodule/xmodule/course_module.py
lms/djangoapps/courseware/models.py
lms/envs/aws.py
lms/envs/common.py
lms/templates/staff_problem_info.html

This is a small PR that adds the changes needed to edx-platform code, to get the webwork xblock working on gingko, as per the instructions/testing from Nathan.

[SE-4754] Changes needed to get webwork xblock working on gingko

---

cms/static/js/views/settings/grading.js
lms/static/js/student_account/components/StudentAccountDeletion.jsx

Rework of PR #73 by @vladimirCampusGovIl

feat: add gettext translation and open accounts on profile del error

---

lms/envs/common.py

Jira: https://campusil.atlassian.net/browse/CAM2-904

chore: [CAM2-904] url to tos page changed to terms-of-service.

---

openedx/core/djangoapps/ace_common/template_context.py
openedx/core/djangoapps/user_authn/views/password_reset.py

https://campusil.atlassian.net/browse/CAM2-918

fix: [CAM2-918] Added url to emails template for platform_name property.

---

lms/templates/main.html

https://campusil.atlassian.net/browse/CAM2-943

feat: [CAM2-943] added notification popup to each page of lms.

---

common/djangoapps/student/views.py
openedx/core/djangoapps/user_api/middleware.py

Jira: https://campusil.atlassian.net/browse/CAM2-986
This feature can be enabled with the Feature Flag "CAMPUS_RESTRICT_COURSE_ACCESS"

feat: [CAM2-986] add middleware to redirect to maintanance page

---

lms/envs/common.py

https://campusil.atlassian.net/browse/CAM2-1050

[chore]: Changes the contact us default url

---

lms/djangoapps/instructor/enrollment.py

https://campusil.atlassian.net/browse/CAM2-1012

fix: [CAM2-1012] repaired emails subject apostrophe case.

---

lms/urls.py

JIRA: https://campusil.atlassian.net/browse/CAM2-1402

fix: [CAM2-1402] reduce the length of 'outcome_service_url' URL

---

common/djangoapps/student/views/management.py

https://campusil.atlassian.net/browse/CAM2-1360

validation message fix bug

---

lms/static/js/student_account/components/PasswordResetConfirmation.jsx
lms/static/js/student_account/views/RegisterView.js

https://campusil.atlassian.net/browse/CAMPUSIL-402

Eden dev custom login register page
