edx-olive/edx-platform-old

lms/djangoapps/courseware/access.py, lms/djangoapps/courseware/tests/test_access.py
This PR hides all ccx courses from the course catalog. Previously the catalog visibility was inherited from the base course at the time of ccx creation, resulting in the possibility of ccx courses to be unexpectedly visible in the catalog.
**Sandbox URL**:
-    LMS: TBD
-    Studio: TBD
**Merge deadline**: None
1. Enable CCX courses (`CUSTOM_COURSES_EDX: true`)
2. go through the process of [creating a custom course](https://edx.readthedocs.io/projects/open-edx-building-and-running-a-course/en/latest/set_up_course/studio_add_course_information/custom_courses.html).
3. log in as a non-staff user and view the course catalog page. the ccx course overview should not be seen.
4. also test with `COURSE_CATALOG_VISIBILITY_PERMISSION` set to …
=> Fix ccx visibility on catalog

common/djangoapps/third_party_auth/settings.py, common/djangoapps/third_party_auth/tests/test_settings.py
This PR fixes the issue of the username hints not working for SSO - Google, FB, SAML.
The fix essentially disables calling the default clean username method which filters out non-ascii characters.
1. Go to https://courses.campus-dev.opencraft.hosting/register?next=/dashboard and login with either MOE SSO/FB/Google credentials.
2. Verify that the username field being auto-filled is correct.
Reviewers:
@pomegranited
=> [SE-1199] Fix username hints for SSO

requirements/edx/github.txt
This PR updates Github requirements to use `open-craft` forks to avoid the risk of deleted repositories.
**Dev URL:**
- LMS: https://courses.campus-dev.opencraft.hosting/
- Studio: https://studio.campus-dev.opencraft.hosting/
**Reviewers**
- @pomegranited
=> [SE-1205] Update Github archived requirements with forked repositories

lms/djangoapps/ccx/tests/test_views.py, lms/djangoapps/ccx/utils.py, lms/djangoapps/ccx/views.py
Previously, unicode would result in a UnicodeEncodeError as a result of
the format string being str instead of unicode.
Additionally, the log calls would crash with a traceback (while not
affecting the program flow).
(cherry picked from commit 54f9434d468be65bd925628a8812bf33349582ca)
**Sandbox**:
-    LMS: https://pr11.sandbox.opencraft.hosting/
-    Studio: https://studio.pr11.sandbox.opencraft.hosting/
**Testing**:
See https://github.com/edx/edx-platform/pull/21248
**Settings**
```yaml
EDXAPP_FEATURES:
CUSTOM_COURSES_EDX: true
ENABLE_UNICODE_USERNAME: true
```
=> SE-1155 Allows unicode usernames to be used in CCX enrollments and reports.

common/lib/xmodule/xmodule/template_module.py
Includes the following patches from https://github.com/open-craft/edx-platform/pull/187 and https://github.com/open-craft/edx-platform/pull/189
* Mako fix (https://github.com/edx/edx-platform/pull/21350) -- clean cherry-pick
**Testing instructions**
Will deploy to stage.campus.gov.il to test.
**Author Notes & Concerns**
Omitted these patches because they are not required for Campus Ginkgo.2:
* [Google cloud API removal](https://github.com/edx/edx-platform/commit/3136b3ecd3bc0d375e8e3f47f850805dc19b70db) and related [YouTube API Referrer fix](https://github.com/open-craft/edx-platform/pull/189/commits/1331d3dfb8ee4a7f65340914786951e12b50c6ed):  `YOUTUBE_API_KEY` not set for Olive edxapp services.
* [Social link platform validation](https://github.com/edx/edx-platform/commit/138b3b35e039ae5a …
=> SE-1499 Merge security patch to Campus Ginkgo.2 branch

common/djangoapps/student/models.py
Fixes issue where users with a Hebrew (unicode) username cannot be deleted from Django Admin. The issue is not an issue with the deletion itself, it's caused by Django's attempts to render the related models that will be deleted on the the Delete User confirmation screen.  The "render to unicode" string methods on these models must use unicode format strings.
**Testing instructions**
Deployed to courses.stage.campus.gov.il
1. Create a user with a Hebrew username, e.g. [this user](https://courses.stage.campus.gov.il/admin/auth/user/50/) (<-- ok to delete).
1. Enrol in a course ([user above has 5 enrollments](https://courses.stage.campus.gov.il/admin/student/courseenrollment/?q=%D7%92%D7%9E%D7%90%D7%9C_%D7%97%D7%98%D7%99%D7%91_1))
1. As a superuser in Django Admin, delete the user created …
=> CAM2-325 Ensure format strings for student models allow unicode usernames

lms/djangoapps/courseware/models.py
Follow-up PR for https://github.com/edx-olive/edx-platform/pull/20
Fixes similar issues with courseware models.
**Testing instructions**
Deploying to courses.campus.gov.il
1. Create a user with a Hebrew username, e.g. [this user](https://courses.campus.gov.il/admin/auth/user/119837/) (<-- ok to delete).
1. From the shell, ensure the user has a related `courseware.models.XModuleStudentPrefsField` record (user above already does)
```python
from courseware.models import XModuleStudentPrefsField
from django.contrib.auth import get_user_model
jamal = get_user_model().objects.get(username='גמאל_חטיב_1')
XModuleStudentPrefsField.objects.create(student=jamal, value=u'"en"', module_type=u'video', field_name=u'transcript_langauge')
```
1. As a superuser in Django Admin, delete the user created in …
=> SE-2451 Ensure courseware models allow unicode rendering

lms/static/js/Markdown.Editor.js
This PR modifies the current forum image upload flow. The image was being uploaded to the configured storage when the user selected a file from the file picker without waiting for confirmation. The upload method will now be called only once the user clicks 'OK' button confirming the selection. 
1. Go to a forum dicussion page in a course and click on 'Add a Post'.
2. In the editor, click on image icon and click 'Choose File' button to open file picker.
3. Select an image file you want to upload.
4. Verify the file name is shown in the text area. Provide a description for the image or enable flag indicating image is decorative only.
5. Click OK. Verify the upload api is called only after OK is clicked and the image is rendered in preview.
**Reviewers:**
**Authors …
=> [SE-2506][CAM2-328] Fix forum image upload

common/lib/xmodule/xmodule/js/spec/video/general_spec.js, common/lib/xmodule/xmodule/js/spec/video/initialize_spec.js, common/lib/xmodule/xmodule/js/spec/video/video_player_spec.js, common/lib/xmodule/xmodule/js/src/video/01_initialize.js, common/lib/xmodule/xmodule/js/src/video/08_video_speed_control.js, common/lib/xmodule/xmodule/js/src/video/095_video_context_menu.js, common/lib/xmodule/xmodule/js/src/video/09_events_plugin.js
(cherry picked from commit a5fe668 - edx/edx-platform#19888)
First, there was a ["fix video player speed adjustments" pull request](https://github.com/edx/edx-platform/pull/19645) merged into the edx-platform. That commit was later on [cherry picked into the `edx-olive/edx-platform:master`](https://github.com/edx-olive/edx-platform/commit/f1237039ee5c82e3ac529e9fe803b621773e93ef).
However, the next month, another [pull request came up "patch video player speed adjustments"](https://github.com/edx/edx-platform/pull/19888). However, this commit was not cherry picked into the [`edx-olive/edx-platform:master`](https://github.com/edx-olive/edx-platform/blob/master/common/lib/xmodule/xmodule/js/src/video/01_initialize.js#L686-L705) or [`edx-olive/edx-platform:pooja/cherry-pick-pymongo-upgrade`]( …
=> [SE-2507] Fixes bug when setting speed in video component

cms/static/js/views/uploads.js
This is an urgent request, therefore I'll be merging now to fix production, and we can work on a better fix later.
The fix is to revert the part of the last PR, https://github.com/edx-olive/edx-platform/pull/32: the part that deals with file uploads.
I tested [in Studio](https://studio.stage.campus.gov.il/container/block-v1:edX+DemoX+Demo_Course+type@vertical+block@d94f702210e64a7aadcaab278631dda7?action=new) that I can now upload transcripts, whereas I couldn't before this patch (I was getting `[object HTMLInputElement]`, as Campus reported).
This old behaviour should be fine because it's what was before https://github.com/edx-olive/edx-platform/pull/32
We'll need to reapply the XSS patch.
=> [SE-3463] Revert part of last commit because the upload widget is broken

openedx/core/djangoapps/user_api/views.py
This PR overrides the fullname attribute of third-party SAML response, if the response does not contain a fullname and only contains first name and last name.
**Jira tickets:** [SE-2377](https://tasks.opencraft.com/browse/SE-2377)
Testing Instructions: Already tested by Campus.
Reviewers:
=> [SE-2377] Override SAML fullname if not present

cms/startup.py, lms/startup.py, openedx/core/djangoapps/monkey_patch/django_contrib_admin_options.py, openedx/core/djangoapps/monkey_patch/tests/test_course_overview_options.py
This PR fixes an issue where attempting to visit Course Overviews in the admin that had course IDs with certain content would throw an error due to issues with the sanitation functions present.
This backports the new version of Django's handling of object ID sanitation which allows it to work with course keys, and monkey patches it in the relevent code.
**JIRA tickets**: https://tasks.opencraft.com/browse/SE-3511 https://lnet-jira.atlassian.net/browse/CAM2-425
**Sandbox URL**: TBD - sandbox is being provisioned.
**Merge deadline**: Tuesday October 27, 2020
1. Check out this version on a campus devstack
2. Comment out the `setattr` lines in the patch.
3. Run `paver test_system -s cms -t openedx.core.djangoapps.monkey_patch.tests` and confirm …
=> [SE-3511] [CAM-425] Fix handling of course keys in admin models.

cms/static/js/views/uploads.js, cms/templates/js/group-configuration-details.underscore, cms/templates/js/maintenance/force-published-course-response.underscore, cms/templates/js/mock/mock-xmodule-editor.underscore, cms/templates/js/publish-editor.underscore, cms/templates/js/unit-outline.underscore, cms/templates/js/video/transcripts/file-upload.underscore, cms/templates/js/xblock-validation-messages.underscore
This combines several security patches, mainly from https://github.com/open-craft/edx-platform/pull/273/ but also https://github.com/open-craft/edx-platform/pull/272 and it also has a small original patch.
We backport all that to the current Campus branch.
We previously reverted part of a XSS patch: https://github.com/edx-olive/edx-platform/pull/35
The proper fix was done upstream: https://github.com/edx/edx-platform/commit/6a0cdf46fc8e0cd74accac9e8fb6109c2f4497e0
This PR cherry-picks that commit, so it should fix the XSS without breaking the uploads.
The rest of the fixes in this PR come from https://github.com/open-craft/edx-platform/pull/273/commits
I'll explain each one in the following sections.
„sustaining security fixes 6“ (XSS patch), …
=> [SE-3463] Apply correction to the last XSS patch and a new XSS patch

lms/djangoapps/grades/tasks.py
Solution suggested at https://discuss.openedx.org/t/problems-with-sga-grade-submission/2415
**Test instructions**:
- ensure persistant grades is enabled
- add an edx-sga block to a course (also add "edx_sga" to advanced modules list)
- set up grading so that the sga block contributes to the final grade, and so does at least one other problem block
- sign up to the course as a student
- complete the problem block
- do whatever required to submit something for the edx-sga block
- as the course instructor, grade the submission on the edx-sga block (navigate to the block in the course view, look for the Grade Submissions button)
- switch back to the student and view the progress page
- verify that the barchart and breakdown correctly show the score (this is important! the individual problem …
=> SE-3566 Match item_type for edx-sga submissions

lms/djangoapps/discussion/tasks.py
This fixes the URL to the discussion thread that is included in forum notification emails.
The problem was that in order for `urljoin` to return an absolute URL, the first argument needs to include the protocol. We were using `site.domain` which doesn't include the protocol.
`urljoin('my.domain.com', '/my/path')` returns `'/my/path'`. We have to makesure to use the full base url (starting with `http(s)://`) and not just the site's domain for generating the discussion thread URL.
**Test instructions**:
1. Login to LMS with a user account and navigate to discussions tab of a particular course that the user is enrolled in.
2. Enable the checkbox is selected in the Receive updates section of the discussion page.
3. Now add a new post but clicking on Add a Post button in the top of the page. …
=> Fix URL in forum notification post.

lms/static/sass/course/_gradebook.scss
This PR fixes RTL scrolling in grade books by removing the absolute positioning of `grade-table` which prevents scrolling if the direction is not LTR.
**Screenshots**: 
https://user-images.githubusercontent.com/19173947/104882909-222e6680-5964-11eb-9495-8f7090d8ce0b.mov
**Merge deadline**: ASAP
1. Open the grade book, referenced in the ticket
2. Find the HTML element with `grade-table` class
3. Remove/turn off the rules removed in this PR
4. Check the site in English
5. Change language to Hebrew and/or Arabic
6. Try again the changes
7. Validate the scrollbar changed
**Author notes and concerns**:
It is normal and expected if the scrollbar jumps to the right within the grade book after the rules are removed and the language is RTL. …
=> [SE-3949] Fix RTL scrolling in grade books

cms/static/cms/js/require-config.js, cms/static/cms/js/spec/main.js, cms/static/cms/js/spec/main_squire.js, common/static/common/js/discussion/mathjax_include.js, common/templates/mathjax_include.html, common/test/acceptance/pages/lms/discussion.py, common/test/acceptance/pages/lms/problem.py, common/test/acceptance/pages/lms/tab_nav.py, lms/static/lms/js/spec/main.js
This is a test to change the default MathJax renderer to CHTML, as requested by Campus, to avoid rending problems like the minus sign.
Upstream already [did a similar change](https://github.com/edx/edx-platform/commit/a59964119f55d228671080ff9da44bb677b99db1) in newer versions.
So: this is code drift, but it's going in the direction that upstream took. Hopefully it won't add much more work to the next upgrade.
It doesn't make sense to add flags or to try to upstream it, since upstream already did the change by themselves.
- More information in the CAM2 ticket.
- This is being tested in Campus stage.
- To do this change, I just replaced the SVG parameter everywhere, and mentioned CHTML
- No clear way to test whether this is fixing the disappearing „minus“ sign, since we don't know how to …
=> [SE-3834] Change MathJax renderer from SVG to CHTML

requirements/edx/base.txt
The version of Py2neo we depend on has been removed from PyPI.  This is
a stop-gap until we can upgrade it
=> fix: ensure py2neo is installed

cms/envs/common.py, common/djangoapps/util/file.py, requirements/edx/base.txt
This pull requests adds a new feature to include CCX course IDs in the generated course filenames used for downloading reports, etc.
The suffix appended to the generated filename prefix is following the  `<separator>_ccx_<ccx id>` pattern, to ensure unique filename generation per ccx - previously all CCX courses were downloaded with the same name.
**Screenshots**: 
**Sandbox URL**: TBD - sandbox is being provisioned.
**Merge deadline**: None
1. Enable `ENABLE_GRADE_DOWNLOADS`, and `ENABLE_COURSE_FILENAME_CCX_SUFFIX` features.
2. Create a course
3. Enable CCX for the course in the advanced settings
4. Create a new CCX for the course
5. Generate and download grades
**Author notes and concerns**:
This PR differs from the upstream PR, since the …
=> [SE-4175] Add CCX ID to generated filenames

.circleci/config.yml, circle.yml
This PR ensures that the circleci uses constraints file while package installation.
=> Make circleci use constraints file

requirements/edx/base.txt
This is required to fix the following issue that started happening in April 1st 2021 in our Ginkgo instance, when sending e-mails:
```
<Error>
<Type>Sender</Type>
<Code>InvalidClientTokenId</Code>
<Message>Signature Version 3 requests are deprecated from March 1, 2021. From that date on, we are progressively rejecting such requests. To resolve the issue you must migrate to Signature Version 4. If you are self-signing your requests, refer to the documentation for Authenticating requests to the Amazon SES API [1] with Signature Version 4 [2]. If you are not self-signing your requests, simply update your SDK/CLI to the latest version. [1] https://docs.aws.amazon.com/ses/latest/DeveloperGuide/using-ses-api-authentication.html [2] https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canon …
```
=> [SE-4333] Update django-ses to a version which supports Signature Version 4

requirements/edx/base.txt, requirements/edx/github.txt, requirements/edx/pre.txt
AMI builds were failing due to python 2.7 being no longer supported. Although the errors showed up suddenly, they have been addressed by the changes below. 
* `mongoengine`, `meliae`, `pa11ycrawler`, and `cryptography` version update was necessary
* `django-rest-framework` repository owner wasn't necessary to change, but it is beneficial for the future
* Adding new requirement dependencies in the `pre.txt` file is because we kept receiving `Could not find suitable distribution for Requirement` for the setup requirements
* `pyandoc` setup requirement was removed in https://github.com/edx-olive/MongoDBProxy because it was causing more trouble than fixing
* For more information: When the `pyandoc` isn't added to the `pre.txt`, we get a `Could not find suitable distribution`. However, once …
=> [SE-4361] Fixes failing AMI builds

lms/djangoapps/instructor_task/api.py, lms/djangoapps/instructor_task/tasks_helper/grades.py, lms/djangoapps/periodic_instructor_reports/tasks.py
This PR extends the periodic instructor reports execution with `submit_problem_grade_report`. 
**Screenshots**: 
**Sandbox URL**: Test in devstack - Sandbox will be provisioned after approval
**Merge deadline**: ASAP
0. Clone the devstack (https://github.com/edx-olive/devstack)
1. In `campus-vars.yml` set `EDXAPP_CELERYBEAT_SCHEDULER: 'djcelery.schedulers.DatabaseScheduler'` and `edx_platform_version:gabor/problem-grade-report-kwargs`
2. Run `vagrant up --provision` to provision a new devstack with the configuration above
3. Start app servers with `paver run_all_servers`
4. Navigate to http://localhost:8000/admin/djcelery/periodictask after all servers started
5. Add a new periodic task shown on the screenshot above
6. Wait 1 minute and …
=> [SE-4370] add submit_problem_grade_report to periodic execution

lms/djangoapps/periodic_instructor_reports/tasks.py
Implement additional folder structure options. This way, users could introduce as many custom subfolders into the S3 folder structure as they need to automate their processes.
**Screenshots**:  N/A
**Sandbox URL**: https://studio.stage.campus.gov.il/admin/
**Merge deadline**: ASAP
* Enable task https://courses.stage.campus.gov.il/admin/djcelery/periodictask/4/
* Wait for the time period (about 1 minute)
* Go to https://courses.stage.campus.gov.il/admin/instructor_task/instructortask/?o=-6
* Check for the latest 5 runs for:
* ccx-v1:OpenCraft+CS101+2020_T1+ccx@29
* ccx-v1:OpenCraft+CS101+2020_T1+ccx@28
* ccx-v1:OpenCraft+CS101+2020_T1+ccx@23
* ccx-v1:OpenCraft+CS101+2020_T1+ccx@19
* course-v1:OpenCraft+CS101+2020_T1
* Check for the related …
=> [SE-4304] feat: add upload folder prefix

requirements/edx/base.txt
This PR adds [`single-beat`](https://github.com/ybrs/single-beat) to the platform requirements used by the [configuration](https://github.com/edx-olive/configuration/pull/31).
**Sandbox URL**: Deployed to stage
**Merge deadline**: ASAP
* Scale stage worker instances up to 10
* Enable task https://courses.stage.campus.gov.il/admin/djcelery/periodictask/4/
* Wait for the time period (about 1 minute)
* Go to https://courses.stage.campus.gov.il/admin/instructor_task/instructortask/?o=-6
* Check for the latest 5 runs for:
* ccx-v1:OpenCraft+CS101+2020_T1+ccx@29
* ccx-v1:OpenCraft+CS101+2020_T1+ccx@28
* ccx-v1:OpenCraft+CS101+2020_T1+ccx@23
* ccx-v1:OpenCraft+CS101+2020_T1+ccx@19
* course-v1:OpenCraft+CS101+2020_T1
* Check for the related reports within the SE-4304 …
=> [SE-4304] chore: add single-beat for celerybeat scheduling

requirements/edx/constraints.txt
Small PR to pin the django-braces version which was resulting in AMI build failures.
=> [SE-4754] Fix failing AMI build

lms/djangoapps/periodic_instructor_reports/tasks.py
`InvalidKeyError` - `opaque_keys:InvalidKeyErrorperiodic_instructor_reports.tasks.periodic_task_wrapper` raised when a course ID is not found in the batch of courses marked for processing.
This issue causes missing reports for all the other courses that are in the same batch with the mentioned course ID. So, if 15 more course IDs are put into the same batch, none of them will produce reports.
**Locally:**
Follow the testing instructions of https://github.com/edx-olive/edx-platform/pull/59 but add an invalid course ID as well to ensure we are filtering for working course IDs only.
=> fix: ensure task is not complaining on course IDs

lms/djangoapps/periodic_instructor_reports/tasks.py
This PR updates the variable name in order to avoid the list being emptied for periodic report generation.
Same as #70
=> [SE-5054] Fix for periodic reports
